---

- name: Gather Facts for use by Icinga2 role
  gather_facts:
    parallel: yes
  tags:
    - icinga2
    - packages

- name: install required gnupg package
  apt: pkg=gnupg state=present
  tags:
    - icinga2
    - packages

- name: Check if Icinga was already installed from debmon
  stat: path=/etc/apt/sources.list.d/debmon_org_debmon.list
  register: icinga_old_package
  tags:
    - icinga2
    - packages

- name: Remove the old Icinga package to force an upgrade
  apt: pkg=icinga2 state=absent
  when: icinga_old_package.stat.exists == True
  tags:
    - icinga2
    - packages

- name: Delete the old Icinga debmon repository
  file: path="/etc/apt/sources.list.d/debmon_org_debmon.list" state=absent
  tags:
    - icinga2
    - packages

- name: Get Icinga Apt Key
  apt_key:
    url: "https://packages.icinga.com/icinga.key"
    state: present
    keyring: "/etc/apt/trusted.gpg.d/icinga.gpg"
  tags:
    - icinga2
    - packages

- name: Configure Icinga Apt Repo
  apt_repository:
    repo="deb [signed-by=/etc/apt/trusted.gpg.d/icinga.gpg] http://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
    update_cache=yes 
    state=present
  tags:
    - icinga2
    - packages

- include_tasks: main-server.yml
  when: "'icinga_servers' in group_names"

- include_tasks: main-node.yml
  when: "'icinga_servers' not in group_names"
