---
- name: restart icinga2
  service: name=icinga2 state=restarted

- name: restart php-fpm
  service: name=php{{ icinga_php_version }}-fpm state=restarted

- name: restart graphite
  service: name=graphite-api state=restarted

- name: restart uwsgi
  service: name=uwsgi state=restarted
